### ISSUE TITLE
App Requirement Issues

### ISSUE THREAD

**Issue by skliper** [nasa/FM#16]
1. LC3002.1.1 & LC3002.2.1 - Don’t see where event filter is able to be specified in Action Point or Watchpoint definition tables.
2.  DS8000 – DS HK packet 
3.  FM4000 – FM HK packet
4. DS3000 - Requirement Incomplete

Imported from GSFCCFS-1917

**Comment by dmknutsen** [comment]
Update to further specify FM requirement issues:

FM4000: 
FM shall generate a housekeeping message containing the following:
a) Valid Command Counter
b) Command Rejected Counter
c) Total number of open files 

FM4000 was updated to the above verbiage since originally flagging it as an issue.  This requirement is currently being tested successfully and there is no longer a requirement violation.  The only potential concern is that the number of open files is treated as a uint32 by FSW, but is telemetered as a uint8 such that truncation may result if the number of open files allowed by OSAL grows.

**Comment by skliper** [comment]
Looks like both the csv and FM_2.6.0_AppRequirementsDocument match what you stated above.
https://github.com/nasa/FM/blob/main/docs/fm_FunctionalRequirements.csv#L46

@dmknutsen Could you open a new issue about the truncation if there isn't one already?  Then we should be able to close this as completed.

**Comment by skliper** [comment]
Truncation issue documented in https://github.com/nasa/FM/issues/27.  This requirements issue was resolve prior to adding requirements cvs, which was done in 47932d26036bead589b4c9cbd23958613760ffc4.
